name: Welcome to the party (action)
description: Welcomes someone to our party

inputs:
  # The value here is how you will reference the input in the job steps
  who_to_greet:
    description: 'What is your name?'
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Truly greet the user
      id: greet-user
      shell: bash
      run: |
        echo "::notice::Hello, ${{ inputs.who_to_greet }} from an action!!!"
