name: Welcome to the party (action)
description: Welcomes someone to our party

inputs:
  # The value here is how you will reference the input in the job steps
  thename:
    description: 'What is your name?'
    type: string
    required: true

runs: composite
steps:
  - name: Truly greet the user
    id: greet-user
    shell: bash
    run: |
      echo "::notice::Hello, ${{ inputs.thename }} from an action!!!"
