name: Welcome to the party (second)
on:
  workflow_dispatch:

jobs:
  say_hello:
    name: "Let's greet the user!"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello there!"
      - uses: actions/checkout@v3
      - run: cat ./.github/workflows/list.txt
      - run: echo "I am step 4!"
