name: Welcome to the party
on:
  workflow_dispatch:
    inputs:
      # The value here is how you will reference the input in the workflow
      thename:
        description: 'What is your name?'
        type: string
        required: true


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "Hello there, ${{ inputs.thename }}!"
